### ISSUE TITLE
important breaks the animations

### ISSUE THREAD

**Issue by avionbg** [bentzibentz/tailwindcss-animate.css#12]
Setting the important: true, for utility classes breaks the animate.css plugin, each animation gets !important at the end of  the definition which isn't supported and animations aren't working.
example:
```js
// tailwind.config.js initial part
module.exports = {
  prefix: '',
  important: true,
  // ...
}
```

compiled css:
```css
@keyframes slideInDown {
  from {
    transform: translate3d(0, -100%, 0) !important;
    visibility: visible !important;
  }

  to {
    transform: translate3d(0, 0, 0) !important;
  }
}
```
